version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: microfrontend-backend
    ports:
      - '5000:5000'
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: microfrontend-frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
